// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wrapper.proto

package com.pkest.netty2.proto;

public final class WrapperOuterClass {
  private WrapperOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.pkest.netty.proto.Wrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes content = 1;</code>
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <code>optional .com.pkest.netty.proto.Wrapper.ContectType contentType = 2;</code>
     */
    int getContentTypeValue();
    /**
     * <code>optional .com.pkest.netty.proto.Wrapper.ContectType contentType = 2;</code>
     */
    WrapperOuterClass.Wrapper.ContectType getContentType();

    /**
     * <code>optional string classType = 3;</code>
     */
    String getClassType();
    /**
     * <code>optional string classType = 3;</code>
     */
    com.google.protobuf.ByteString
        getClassTypeBytes();
  }
  /**
   * Protobuf type {@code com.pkest.netty.proto.Wrapper}
   */
  public  static final class Wrapper extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.pkest.netty.proto.Wrapper)
      WrapperOrBuilder {
    // Use Wrapper.newBuilder() to construct.
    private Wrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Wrapper() {
      content_ = com.google.protobuf.ByteString.EMPTY;
      contentType_ = 0;
      classType_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Wrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              content_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              contentType_ = rawValue;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              classType_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return WrapperOuterClass.internal_static_com_pkest_netty_proto_Wrapper_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return WrapperOuterClass.internal_static_com_pkest_netty_proto_Wrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              WrapperOuterClass.Wrapper.class, WrapperOuterClass.Wrapper.Builder.class);
    }

    /**
     * Protobuf enum {@code com.pkest.netty.proto.Wrapper.ContectType}
     */
    public enum ContectType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>BYTE = 0;</code>
       */
      BYTE(0),
      /**
       * <code>INT = 1;</code>
       */
      INT(1),
      /**
       * <code>STRING = 2;</code>
       */
      STRING(2),
      /**
       * <code>OBJECT = 3;</code>
       */
      OBJECT(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>BYTE = 0;</code>
       */
      public static final int BYTE_VALUE = 0;
      /**
       * <code>INT = 1;</code>
       */
      public static final int INT_VALUE = 1;
      /**
       * <code>STRING = 2;</code>
       */
      public static final int STRING_VALUE = 2;
      /**
       * <code>OBJECT = 3;</code>
       */
      public static final int OBJECT_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static ContectType valueOf(int value) {
        return forNumber(value);
      }

      public static ContectType forNumber(int value) {
        switch (value) {
          case 0: return BYTE;
          case 1: return INT;
          case 2: return STRING;
          case 3: return OBJECT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ContectType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ContectType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ContectType>() {
              public ContectType findValueByNumber(int number) {
                return ContectType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return WrapperOuterClass.Wrapper.getDescriptor().getEnumTypes().get(0);
      }

      private static final ContectType[] VALUES = values();

      public static ContectType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ContectType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.pkest.netty.proto.Wrapper.ContectType)
    }

    public static final int CONTENT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>optional bytes content = 1;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    public static final int CONTENTTYPE_FIELD_NUMBER = 2;
    private int contentType_;
    /**
     * <code>optional .com.pkest.netty.proto.Wrapper.ContectType contentType = 2;</code>
     */
    public int getContentTypeValue() {
      return contentType_;
    }
    /**
     * <code>optional .com.pkest.netty.proto.Wrapper.ContectType contentType = 2;</code>
     */
    public WrapperOuterClass.Wrapper.ContectType getContentType() {
      WrapperOuterClass.Wrapper.ContectType result = WrapperOuterClass.Wrapper.ContectType.valueOf(contentType_);
      return result == null ? WrapperOuterClass.Wrapper.ContectType.UNRECOGNIZED : result;
    }

    public static final int CLASSTYPE_FIELD_NUMBER = 3;
    private volatile Object classType_;
    /**
     * <code>optional string classType = 3;</code>
     */
    public String getClassType() {
      Object ref = classType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        classType_ = s;
        return s;
      }
    }
    /**
     * <code>optional string classType = 3;</code>
     */
    public com.google.protobuf.ByteString
        getClassTypeBytes() {
      Object ref = classType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        classType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!content_.isEmpty()) {
        output.writeBytes(1, content_);
      }
      if (contentType_ != WrapperOuterClass.Wrapper.ContectType.BYTE.getNumber()) {
        output.writeEnum(2, contentType_);
      }
      if (!getClassTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, classType_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, content_);
      }
      if (contentType_ != WrapperOuterClass.Wrapper.ContectType.BYTE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, contentType_);
      }
      if (!getClassTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, classType_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof WrapperOuterClass.Wrapper)) {
        return super.equals(obj);
      }
      WrapperOuterClass.Wrapper other = (WrapperOuterClass.Wrapper) obj;

      boolean result = true;
      result = result && getContent()
          .equals(other.getContent());
      result = result && contentType_ == other.contentType_;
      result = result && getClassType()
          .equals(other.getClassType());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + CONTENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + contentType_;
      hash = (37 * hash) + CLASSTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getClassType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static WrapperOuterClass.Wrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WrapperOuterClass.Wrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WrapperOuterClass.Wrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WrapperOuterClass.Wrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WrapperOuterClass.Wrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static WrapperOuterClass.Wrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static WrapperOuterClass.Wrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static WrapperOuterClass.Wrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static WrapperOuterClass.Wrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static WrapperOuterClass.Wrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(WrapperOuterClass.Wrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.pkest.netty.proto.Wrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.pkest.netty.proto.Wrapper)
        WrapperOuterClass.WrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return WrapperOuterClass.internal_static_com_pkest_netty_proto_Wrapper_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return WrapperOuterClass.internal_static_com_pkest_netty_proto_Wrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                WrapperOuterClass.Wrapper.class, WrapperOuterClass.Wrapper.Builder.class);
      }

      // Construct using com.pkest.netty.proto.WrapperOuterClass.Wrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        content_ = com.google.protobuf.ByteString.EMPTY;

        contentType_ = 0;

        classType_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return WrapperOuterClass.internal_static_com_pkest_netty_proto_Wrapper_descriptor;
      }

      public WrapperOuterClass.Wrapper getDefaultInstanceForType() {
        return WrapperOuterClass.Wrapper.getDefaultInstance();
      }

      public WrapperOuterClass.Wrapper build() {
        WrapperOuterClass.Wrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public WrapperOuterClass.Wrapper buildPartial() {
        WrapperOuterClass.Wrapper result = new WrapperOuterClass.Wrapper(this);
        result.content_ = content_;
        result.contentType_ = contentType_;
        result.classType_ = classType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof WrapperOuterClass.Wrapper) {
          return mergeFrom((WrapperOuterClass.Wrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(WrapperOuterClass.Wrapper other) {
        if (other == WrapperOuterClass.Wrapper.getDefaultInstance()) return this;
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        if (other.contentType_ != 0) {
          setContentTypeValue(other.getContentTypeValue());
        }
        if (!other.getClassType().isEmpty()) {
          classType_ = other.classType_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        WrapperOuterClass.Wrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (WrapperOuterClass.Wrapper) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes content = 1;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>optional bytes content = 1;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }

        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes content = 1;</code>
       */
      public Builder clearContent() {

        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      private int contentType_ = 0;
      /**
       * <code>optional .com.pkest.netty.proto.Wrapper.ContectType contentType = 2;</code>
       */
      public int getContentTypeValue() {
        return contentType_;
      }
      /**
       * <code>optional .com.pkest.netty.proto.Wrapper.ContectType contentType = 2;</code>
       */
      public Builder setContentTypeValue(int value) {
        contentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.pkest.netty.proto.Wrapper.ContectType contentType = 2;</code>
       */
      public WrapperOuterClass.Wrapper.ContectType getContentType() {
        WrapperOuterClass.Wrapper.ContectType result = WrapperOuterClass.Wrapper.ContectType.valueOf(contentType_);
        return result == null ? WrapperOuterClass.Wrapper.ContectType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .com.pkest.netty.proto.Wrapper.ContectType contentType = 2;</code>
       */
      public Builder setContentType(WrapperOuterClass.Wrapper.ContectType value) {
        if (value == null) {
          throw new NullPointerException();
        }

        contentType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.pkest.netty.proto.Wrapper.ContectType contentType = 2;</code>
       */
      public Builder clearContentType() {

        contentType_ = 0;
        onChanged();
        return this;
      }

      private Object classType_ = "";
      /**
       * <code>optional string classType = 3;</code>
       */
      public String getClassType() {
        Object ref = classType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          classType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string classType = 3;</code>
       */
      public com.google.protobuf.ByteString
          getClassTypeBytes() {
        Object ref = classType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          classType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string classType = 3;</code>
       */
      public Builder setClassType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        classType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string classType = 3;</code>
       */
      public Builder clearClassType() {

        classType_ = getDefaultInstance().getClassType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string classType = 3;</code>
       */
      public Builder setClassTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        classType_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.pkest.netty.proto.Wrapper)
    }

    // @@protoc_insertion_point(class_scope:com.pkest.netty.proto.Wrapper)
    private static final WrapperOuterClass.Wrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new WrapperOuterClass.Wrapper();
    }

    public static WrapperOuterClass.Wrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Wrapper>
        PARSER = new com.google.protobuf.AbstractParser<Wrapper>() {
      public Wrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Wrapper(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Wrapper> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Wrapper> getParserForType() {
      return PARSER;
    }

    public WrapperOuterClass.Wrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pkest_netty_proto_Wrapper_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pkest_netty_proto_Wrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rWrapper.proto\022\025com.pkest.netty.proto\"\250" +
      "\001\n\007Wrapper\022\017\n\007content\030\001 \001(\014\022?\n\013contentTy" +
      "pe\030\002 \001(\0162*.com.pkest.netty.proto.Wrapper" +
      ".ContectType\022\021\n\tclassType\030\003 \001(\t\"8\n\013Conte" +
      "ctType\022\010\n\004BYTE\020\000\022\007\n\003INT\020\001\022\n\n\006STRING\020\002\022\n\n" +
      "\006OBJECT\020\003B\027\n\025com.pkest.netty.protob\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_pkest_netty_proto_Wrapper_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_pkest_netty_proto_Wrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pkest_netty_proto_Wrapper_descriptor,
        new String[] { "Content", "ContentType", "ClassType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
